#!/usr/bin/env sh
# Exports the compiled ABIs into frontend/src/abi.
#
# v1 pasted the ABIs by hand inside the React components (~1,400 of src/'s
# 1,700 lines), so any contract change silently left them out of sync. Here
# they are regenerated from forge's artifacts, which are the single source of
# truth.
#
#   ./export-abis.sh
set -eu

cd "$(dirname "$0")"
OUT="../frontend/src/abi"
mkdir -p "$OUT"

forge build --silent

for name in CollateralVotingVault GovStablecoin DelegationAccount MockGovernanceToken; do
  printf '// Generated by contracts/export-abis.sh. Do not edit by hand.\n' > "$OUT/$name.json.js"
  printf 'export const %sAbi = ' "$(printf '%s' "$name" | cut -c1 | tr '[:upper:]' '[:lower:]')$(printf '%s' "$name" | cut -c2-)" >> "$OUT/$name.json.js"
  forge inspect "$name" abi --json >> "$OUT/$name.json.js"
  printf ';\n' >> "$OUT/$name.json.js"
  mv "$OUT/$name.json.js" "$OUT/$name.js"
  echo "  $OUT/$name.js"
done

echo "ABIs exported."
